# Generated by Django 5.1.1 on 2025-01-11 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('asset_type', models.CharField(choices=[('Stock', 'Stock'), ('Bond', 'Bond'), ('Derivative', 'Derivative'), ('ETF', 'ETF'), ('Mutual Fund', 'Mutual Fund')], max_length=100)),
                ('buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('number_assets', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='N/A', max_length=10)),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('asset_type', models.CharField(default='Stock', max_length=100)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_market_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio',
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
