# Generated by Django 5.1.1 on 2025-01-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
