# Generated by Django 5.1.1 on 2025-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_transaction_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'portfolio_history',
            },
        ),
    ]
